// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexaWorks.Data;

#nullable disable

namespace NexaWorks.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260908074814_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexaWorks.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            NameProduct = "Trader en Herbe"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            NameProduct = "Maître des Investissements"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            NameProduct = "Planificateur d’Entraînement"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            NameProduct = "Planificateur d’Anxiété Sociale"
                        });
                });

            modelBuilder.Entity("NexaWorks.Entities.Resolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("ResolutionDate")
                        .HasColumnType("date");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("Resolutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Il manquait un composant système sur l'ordinateur de l'utilisateur. Envoi de la marche à suivre pour installer le composant manquant et mise à jour du guide d'installation.",
                            IsDeleted = false,
                            ResolutionDate = new DateOnly(2023, 1, 12),
                            TicketId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "L'utilisateur avait activé le mode sombre de son ordinateur. Demande envoyée à l'équipe technique pour que les couleurs du logiciel s'adaptent automatiquement au mode sombre.",
                            IsDeleted = false,
                            ResolutionDate = new DateOnly(2023, 2, 5),
                            TicketId = 3
                        },
                        new
                        {
                            Id = 3,
                            Description = "Le graphique accumulait trop d'informations en mémoire sans se nettoyer. Une mise à jour a été envoyée pour corriger ce comportement.",
                            IsDeleted = false,
                            ResolutionDate = new DateOnly(2023, 3, 22),
                            TicketId = 5
                        },
                        new
                        {
                            Id = 4,
                            Description = "Un réglage d'affichage empêchait les données d'apparaître sur le document avant impression. Un correctif a été appliqué.",
                            IsDeleted = false,
                            ResolutionDate = new DateOnly(2023, 4, 14),
                            TicketId = 7
                        },
                        new
                        {
                            Id = 5,
                            Description = "La banque avait changé sa procédure de sécurité. L'application a été mise à jour pour s'adapter aux nouvelles règles de la banque.",
                            IsDeleted = false,
                            ResolutionDate = new DateOnly(2023, 5, 3),
                            TicketId = 9
                        },
                        new
                        {
                            Id = 6,
                            Description = "La session de l'utilisateur avait expiré en arrière-plan sans l'avertir. L'utilisateur s'est déconnecté puis reconnecté pour valider sa modification.",
                            IsDeleted = false,
                            ResolutionDate = new DateOnly(2023, 5, 17),
                            TicketId = 11
                        },
                        new
                        {
                            Id = 7,
                            Description = "Le logiciel mettait le flux en pause automatique. Une option a été ajoutée pour permettre au flux de continuer à se mettre à jour en arrière-plan.",
                            IsDeleted = false,
                            ResolutionDate = new DateOnly(2023, 5, 29),
                            TicketId = 13
                        },
                        new
                        {
                            Id = 8,
                            Description = "Le logiciel cherchait à jouer un son de bienvenue obligatoirement. Le problème a été corrigé pour que le son soit ignoré si aucun matériel audio n'est présent.",
                            IsDeleted = false,
                            ResolutionDate = new DateOnly(2023, 6, 10),
                            TicketId = 15
                        },
                        new
                        {
                            Id = 9,
                            Description = "L'utilisateur n'avait pas coché la case d'autorisation dans les réglages de son téléphone. Guidage de l'utilisateur pas à pas pour activer l'option.",
                            IsDeleted = false,
                            ResolutionDate = new DateOnly(2023, 6, 19),
                            TicketId = 17
                        },
                        new
                        {
                            Id = 10,
                            Description = "Un problème de sauvegarde des préférences a été corrigé. Les choix de l'utilisateur sont désormais bien enregistrés.",
                            IsDeleted = false,
                            ResolutionDate = new DateOnly(2023, 6, 28),
                            TicketId = 19
                        },
                        new
                        {
                            Id = 11,
                            Description = "La zone de texte avait une limite de taille trop petite. La limite a été retirée pour permettre des textes plus longs.",
                            IsDeleted = false,
                            ResolutionDate = new DateOnly(2023, 7, 9),
                            TicketId = 21
                        },
                        new
                        {
                            Id = 12,
                            Description = "L'application a été adaptée pour pouvoir consulter ses anciens messages même sans connexion Internet.",
                            IsDeleted = false,
                            ResolutionDate = new DateOnly(2023, 7, 18),
                            TicketId = 23
                        },
                        new
                        {
                            Id = 13,
                            Description = "Aucune application de gestion de fichiers compatible n'était configurée sur le téléphone. Un message explicite a été ajouté pour avertir l'utilisateur d'exporter ou de sauvegarder au format PDF.",
                            IsDeleted = false,
                            ResolutionDate = new DateOnly(2023, 7, 27),
                            TicketId = 25
                        });
                });

            modelBuilder.Entity("NexaWorks.Entities.StatusTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusTicket");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Title = "En cours"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Title = "Résolu"
                        });
                });

            modelBuilder.Entity("NexaWorks.Entities.SystemOs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NameSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemsOs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            NameSystem = "Linux"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            NameSystem = "MacOS"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            NameSystem = "Windows"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            NameSystem = "Android"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            NameSystem = "iOS"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            NameSystem = "Windows Mobile"
                        });
                });

            modelBuilder.Entity("NexaWorks.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("StatusTicketId")
                        .HasColumnType("int");

                    b.Property<int>("VersionOsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusTicketId");

                    b.HasIndex("VersionOsId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateOnly(2023, 1, 10),
                            Description = "L'utilisateur indique que le logiciel ne se lance pas du tout lorsqu'il clique sur l'icône depuis son bureau. Rien ne s'affiche à l'écran.",
                            IsDeleted = false,
                            StatusTicketId = 2,
                            VersionOsId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateOnly(2023, 1, 15),
                            Description = "L'utilisateur tente d'importer la liste de ses investissements depuis un fichier texte, mais le logiciel affiche un message d'erreur indiquant que le fichier est illisible.",
                            IsDeleted = false,
                            StatusTicketId = 1,
                            VersionOsId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateOnly(2023, 2, 1),
                            Description = "L'utilisateur n'arrive pas à lire les noms des actions sur son écran car le texte s'affiche en noir sur un fond gris foncé.",
                            IsDeleted = false,
                            StatusTicketId = 2,
                            VersionOsId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateOnly(2023, 3, 10),
                            Description = "L'utilisateur ne reçoit aucune notification sur son ordinateur lorsque le prix d'une action atteint le seuil qu'il a défini.",
                            IsDeleted = false,
                            StatusTicketId = 1,
                            VersionOsId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateOnly(2023, 3, 20),
                            Description = "L'application devient très lente puis se ferme toute seule si on laisse le graphique des prix ouvert pendant plus de 20 minutes.",
                            IsDeleted = false,
                            StatusTicketId = 2,
                            VersionOsId = 8
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateOnly(2023, 4, 5),
                            Description = "Lors d'une tentative de vente d'actions, la validation par reconnaissance faciale ne réagit pas et la vente reste bloquée.",
                            IsDeleted = false,
                            StatusTicketId = 1,
                            VersionOsId = 11
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateOnly(2023, 4, 12),
                            Description = "L'utilisateur demande à générer son récapitulatif annuel de gains en PDF pour le partager, mais le document généré sort entièrement vierge.",
                            IsDeleted = false,
                            StatusTicketId = 2,
                            VersionOsId = 11
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateOnly(2023, 4, 25),
                            Description = "Si l'utilisateur tourne son téléphone sur le côté pour mettre l'écran à l'horizontale pendant le chargement des données, l'écran reste bloqué.",
                            IsDeleted = false,
                            StatusTicketId = 1,
                            VersionOsId = 14
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateOnly(2023, 4, 28),
                            Description = "L'utilisateur ne parvient pas à connecter son compte bancaire à l'application. Un message indique que la liaison a échoué.",
                            IsDeleted = false,
                            StatusTicketId = 2,
                            VersionOsId = 15
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateOnly(2023, 5, 10),
                            Description = "L'ordinateur de l'utilisateur se met à chauffer fortement et le ventilateur fait du bruit dès que la rubrique \"Dividendes\" reste ouverte.",
                            IsDeleted = false,
                            StatusTicketId = 1,
                            VersionOsId = 16
                        },
                        new
                        {
                            Id = 11,
                            CreationDate = new DateOnly(2023, 5, 15),
                            Description = "L'utilisateur tente de modifier son adresse e-mail dans son profil, mais le logiciel lui refuse l'accès en disant qu'il n'a pas les droits nécessaires.",
                            IsDeleted = false,
                            StatusTicketId = 2,
                            VersionOsId = 17
                        },
                        new
                        {
                            Id = 12,
                            CreationDate = new DateOnly(2023, 5, 22),
                            Description = "Sur le graphique des prévisions, les montants financiers très élevés sont coupés sur la droite de l'écran et on ne voit pas les derniers chiffres.",
                            IsDeleted = false,
                            StatusTicketId = 1,
                            VersionOsId = 19
                        },
                        new
                        {
                            Id = 13,
                            CreationDate = new DateOnly(2023, 5, 28),
                            Description = "L'affichage du cours en temps réel se fige dès que l'utilisateur clique sur une autre fenêtre de son ordinateur.",
                            IsDeleted = false,
                            StatusTicketId = 2,
                            VersionOsId = 22
                        },
                        new
                        {
                            Id = 14,
                            CreationDate = new DateOnly(2023, 6, 2),
                            Description = "L'utilisateur n'arrive pas à synchroniser son compte bancaire secondaire avec le logiciel. Le compte n'est pas détecté lors de la recherche.",
                            IsDeleted = false,
                            StatusTicketId = 1,
                            VersionOsId = 24
                        },
                        new
                        {
                            Id = 15,
                            CreationDate = new DateOnly(2023, 6, 8),
                            Description = "Le logiciel se ferme brutalement à l'ouverture si aucun casque ou haut-parleur n'est branché sur l'ordinateur.",
                            IsDeleted = false,
                            StatusTicketId = 2,
                            VersionOsId = 25
                        },
                        new
                        {
                            Id = 16,
                            CreationDate = new DateOnly(2023, 6, 14),
                            Description = "L'enregistrement du parcours de course à pied s'interrompt brusquement au bout de 10 minutes d'activité et ne trace plus la carte.",
                            IsDeleted = false,
                            StatusTicketId = 1,
                            VersionOsId = 32
                        },
                        new
                        {
                            Id = 17,
                            CreationDate = new DateOnly(2023, 6, 18),
                            Description = "Impossible de partager ses séances de sport avec l'application de santé du téléphone, un message bloque l'autorisation.",
                            IsDeleted = false,
                            StatusTicketId = 2,
                            VersionOsId = 30
                        },
                        new
                        {
                            Id = 18,
                            CreationDate = new DateOnly(2023, 6, 23),
                            Description = "Les vidéos montrant comment réaliser les étirements refusent de se lancer et affichent un écran noir.",
                            IsDeleted = false,
                            StatusTicketId = 1,
                            VersionOsId = 33
                        },
                        new
                        {
                            Id = 19,
                            CreationDate = new DateOnly(2023, 6, 27),
                            Description = "L'utilisateur décoche l'option d'envoi de statistiques anonymes, mais l'option se re-coche toute seule lorsqu'il redémarre le logiciel.",
                            IsDeleted = false,
                            StatusTicketId = 2,
                            VersionOsId = 34
                        },
                        new
                        {
                            Id = 20,
                            CreationDate = new DateOnly(2023, 7, 2),
                            Description = "Les rappels quotidiens pour faire les exercices de relaxation arrivent sur le téléphone avec plusieurs heures de retard par rapport à l'heure programmée.",
                            IsDeleted = false,
                            StatusTicketId = 1,
                            VersionOsId = 36
                        },
                        new
                        {
                            Id = 21,
                            CreationDate = new DateOnly(2023, 7, 6),
                            Description = "L'utilisateur ne peut plus taper de texte dans son journal personnel dès qu'il atteint une cinquantaine de lignes.",
                            IsDeleted = false,
                            StatusTicketId = 2,
                            VersionOsId = 37
                        },
                        new
                        {
                            Id = 22,
                            CreationDate = new DateOnly(2023, 7, 12),
                            Description = "Lors de l'exportation du bilan mensuel sous forme de document, les émojis utilisés pour exprimer l'humeur apparaissent sous forme de petits carrés vides.",
                            IsDeleted = false,
                            StatusTicketId = 1,
                            VersionOsId = 39
                        },
                        new
                        {
                            Id = 23,
                            CreationDate = new DateOnly(2023, 7, 16),
                            Description = "L'application se ferme immédiatement si l'utilisateur l'ouvre alors qu'il n'a pas de connexion Internet (Wi-Fi désactivé ou câble débranché).",
                            IsDeleted = false,
                            StatusTicketId = 2,
                            VersionOsId = 38
                        },
                        new
                        {
                            Id = 24,
                            CreationDate = new DateOnly(2023, 7, 20),
                            Description = "Sur la page du bilan de la semaine, la courbe d'évolution affiche des symboles incompréhensibles au lieu du pourcentage de réussite.",
                            IsDeleted = false,
                            StatusTicketId = 1,
                            VersionOsId = 42
                        },
                        new
                        {
                            Id = 25,
                            CreationDate = new DateOnly(2023, 7, 24),
                            Description = "Lorsque l'utilisateur clique sur le bouton pour exporter ses conseils du jour, rien ne se passe et aucun message n'indique ce qui bloque.",
                            IsDeleted = false,
                            StatusTicketId = 2,
                            VersionOsId = 44
                        });
                });

            modelBuilder.Entity("NexaWorks.Entities.VersionOs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("SystemOsId")
                        .HasColumnType("int");

                    b.Property<int>("VersionProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemOsId");

                    b.HasIndex("VersionProductId");

                    b.ToTable("VersionsOs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            SystemOsId = 1,
                            VersionProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            SystemOsId = 3,
                            VersionProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            SystemOsId = 1,
                            VersionProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            SystemOsId = 2,
                            VersionProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            SystemOsId = 3,
                            VersionProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            SystemOsId = 1,
                            VersionProductId = 3
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            SystemOsId = 2,
                            VersionProductId = 3
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            SystemOsId = 3,
                            VersionProductId = 3
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            SystemOsId = 4,
                            VersionProductId = 3
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            SystemOsId = 5,
                            VersionProductId = 3
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            SystemOsId = 6,
                            VersionProductId = 3
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            SystemOsId = 2,
                            VersionProductId = 4
                        },
                        new
                        {
                            Id = 13,
                            IsDeleted = false,
                            SystemOsId = 3,
                            VersionProductId = 4
                        },
                        new
                        {
                            Id = 14,
                            IsDeleted = false,
                            SystemOsId = 4,
                            VersionProductId = 4
                        },
                        new
                        {
                            Id = 15,
                            IsDeleted = false,
                            SystemOsId = 5,
                            VersionProductId = 4
                        },
                        new
                        {
                            Id = 16,
                            IsDeleted = false,
                            SystemOsId = 2,
                            VersionProductId = 5
                        },
                        new
                        {
                            Id = 17,
                            IsDeleted = false,
                            SystemOsId = 5,
                            VersionProductId = 5
                        },
                        new
                        {
                            Id = 18,
                            IsDeleted = false,
                            SystemOsId = 2,
                            VersionProductId = 6
                        },
                        new
                        {
                            Id = 19,
                            IsDeleted = false,
                            SystemOsId = 4,
                            VersionProductId = 6
                        },
                        new
                        {
                            Id = 20,
                            IsDeleted = false,
                            SystemOsId = 5,
                            VersionProductId = 6
                        },
                        new
                        {
                            Id = 21,
                            IsDeleted = false,
                            SystemOsId = 2,
                            VersionProductId = 7
                        },
                        new
                        {
                            Id = 22,
                            IsDeleted = false,
                            SystemOsId = 3,
                            VersionProductId = 7
                        },
                        new
                        {
                            Id = 23,
                            IsDeleted = false,
                            SystemOsId = 4,
                            VersionProductId = 7
                        },
                        new
                        {
                            Id = 24,
                            IsDeleted = false,
                            SystemOsId = 5,
                            VersionProductId = 7
                        },
                        new
                        {
                            Id = 25,
                            IsDeleted = false,
                            SystemOsId = 1,
                            VersionProductId = 8
                        },
                        new
                        {
                            Id = 26,
                            IsDeleted = false,
                            SystemOsId = 2,
                            VersionProductId = 8
                        },
                        new
                        {
                            Id = 27,
                            IsDeleted = false,
                            SystemOsId = 1,
                            VersionProductId = 9
                        },
                        new
                        {
                            Id = 28,
                            IsDeleted = false,
                            SystemOsId = 2,
                            VersionProductId = 9
                        },
                        new
                        {
                            Id = 29,
                            IsDeleted = false,
                            SystemOsId = 3,
                            VersionProductId = 9
                        },
                        new
                        {
                            Id = 30,
                            IsDeleted = false,
                            SystemOsId = 4,
                            VersionProductId = 9
                        },
                        new
                        {
                            Id = 31,
                            IsDeleted = false,
                            SystemOsId = 5,
                            VersionProductId = 9
                        },
                        new
                        {
                            Id = 32,
                            IsDeleted = false,
                            SystemOsId = 6,
                            VersionProductId = 9
                        },
                        new
                        {
                            Id = 33,
                            IsDeleted = false,
                            SystemOsId = 2,
                            VersionProductId = 10
                        },
                        new
                        {
                            Id = 34,
                            IsDeleted = false,
                            SystemOsId = 3,
                            VersionProductId = 10
                        },
                        new
                        {
                            Id = 35,
                            IsDeleted = false,
                            SystemOsId = 4,
                            VersionProductId = 10
                        },
                        new
                        {
                            Id = 36,
                            IsDeleted = false,
                            SystemOsId = 5,
                            VersionProductId = 10
                        },
                        new
                        {
                            Id = 37,
                            IsDeleted = false,
                            SystemOsId = 2,
                            VersionProductId = 11
                        },
                        new
                        {
                            Id = 38,
                            IsDeleted = false,
                            SystemOsId = 3,
                            VersionProductId = 11
                        },
                        new
                        {
                            Id = 39,
                            IsDeleted = false,
                            SystemOsId = 4,
                            VersionProductId = 11
                        },
                        new
                        {
                            Id = 40,
                            IsDeleted = false,
                            SystemOsId = 5,
                            VersionProductId = 11
                        },
                        new
                        {
                            Id = 41,
                            IsDeleted = false,
                            SystemOsId = 2,
                            VersionProductId = 12
                        },
                        new
                        {
                            Id = 42,
                            IsDeleted = false,
                            SystemOsId = 3,
                            VersionProductId = 12
                        },
                        new
                        {
                            Id = 43,
                            IsDeleted = false,
                            SystemOsId = 4,
                            VersionProductId = 12
                        },
                        new
                        {
                            Id = 44,
                            IsDeleted = false,
                            SystemOsId = 5,
                            VersionProductId = 12
                        });
                });

            modelBuilder.Entity("NexaWorks.Entities.VersionProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("RefVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("VersionProducts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            ProductId = 1,
                            RefVersion = "1.0"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            ProductId = 1,
                            RefVersion = "1.1"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            ProductId = 1,
                            RefVersion = "1.2"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            ProductId = 1,
                            RefVersion = "1.3"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            ProductId = 2,
                            RefVersion = "1.0"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            ProductId = 2,
                            RefVersion = "2.0"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            ProductId = 2,
                            RefVersion = "2.1"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            ProductId = 3,
                            RefVersion = "1.0"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            ProductId = 3,
                            RefVersion = "1.1"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            ProductId = 3,
                            RefVersion = "2.0"
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            ProductId = 4,
                            RefVersion = "1.0"
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            ProductId = 4,
                            RefVersion = "1.1"
                        });
                });

            modelBuilder.Entity("NexaWorks.Entities.Resolution", b =>
                {
                    b.HasOne("NexaWorks.Entities.Ticket", null)
                        .WithOne("Resolution")
                        .HasForeignKey("NexaWorks.Entities.Resolution", "TicketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("NexaWorks.Entities.Ticket", b =>
                {
                    b.HasOne("NexaWorks.Entities.StatusTicket", "StatusTicket")
                        .WithMany()
                        .HasForeignKey("StatusTicketId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NexaWorks.Entities.VersionOs", "VersionOs")
                        .WithMany()
                        .HasForeignKey("VersionOsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("StatusTicket");

                    b.Navigation("VersionOs");
                });

            modelBuilder.Entity("NexaWorks.Entities.VersionOs", b =>
                {
                    b.HasOne("NexaWorks.Entities.SystemOs", "SystemOs")
                        .WithMany()
                        .HasForeignKey("SystemOsId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("NexaWorks.Entities.VersionProduct", "VersionProduct")
                        .WithMany()
                        .HasForeignKey("VersionProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SystemOs");

                    b.Navigation("VersionProduct");
                });

            modelBuilder.Entity("NexaWorks.Entities.VersionProduct", b =>
                {
                    b.HasOne("NexaWorks.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NexaWorks.Entities.Ticket", b =>
                {
                    b.Navigation("Resolution");
                });
#pragma warning restore 612, 618
        }
    }
}
